parameters:
    daps_ldap.ldap.admin.dn: cn=admin,dc=example,dc=com
    daps_ldap.ldap.admin.password: root
    daps_ldap.ldap.admin.enable: true
    daps_ldap.ldap.host: ldap://example.com
    daps_ldap.ldap.port: 389
    daps_ldap.ldap.dn: uid
    daps_ldap.ldap.username_suffix: dc=example,dc=com
